# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI pipeline saucedemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # 1. checkout repo:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. setup jdk
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. setup gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # 4. setup gradle run on container
    - name: Set permissions for gradlew
      run: chmod +x ./gradlew

    # 5. setup build gradle
    - name: Build with Gradle
      run: ./gradlew build

    # 6. setup chrome
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.0
      with:
        chrome-version: stable

    # 7. setup run test
    - name: Run Tests
      run: ./gradlew clean test cucumber

    # 8. Generate Allure Report
    - name: Generate Allure Report
      run: ./gradlew allureReport --clean

    # 9. upload problem report
    - name: Upload Gradle problems report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gradle-problems-report
        path: build/reports/problems/problems-report.html






        

   


